# See https://wiki.archlinux.org/index.php/Systemd-boot
---
- name: Bootloader configuration
  become: yes
  copy:
    dest: /boot/loader/loader.conf
    content: |
      default  arch
      editor   no

- name: Arch Linux bootloader
  become: yes
  copy:
    dest: /boot/loader/entries/arch.conf
    content: |
      title   Arch Linux
      linux   /vmlinuz-linux
      initrd  /intel-ucode.img
      initrd  /initramfs-linux.img
      options root=LABEL=ArchLinux rw

# See https://wiki.archlinux.org/index.php/System_maintenance#Install_the_linux-lts_package
- name: Install LTS kernel
  become: yes
  pacman:
    name: linux-lts
    state: present

- name: Arch Linux (LTS) bootloader
  become: yes
  copy:
    dest: /boot/loader/entries/arch-lts.conf
    content: |
      title   Arch Linux (LTS)
      linux   /vmlinuz-linux-lts
      initrd  /intel-ucode.img
      initrd  /initramfs-linux-lts.img
      options root=LABEL=ArchLinux rw
