---
# All tasks w.r.t developing Java applications

- name: Java packages
  become: yes
  package:
    name:
      - docker
      - docker-compose
      - gradle
      - groovy
      - jdk10-openjdk
      - maven
      - kotlin
    state: present

- name: Java packagescomponents (AUR)
  aur:
    name:
      - intellij-idea-ultimate-edition
      - visual-studio-code-bin
    skip_installed: yes
  when: ansible_distribution == 'Archlinux'
